version: '3'

services:
  app:
    container_name: symfony.app
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache

  nginx:
    image: nginx
    container_name: symfony.nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www/symfony:cached
    ports:
      - "81:80"

  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=symfony
    volumes:
      - ./var/tmp/db:/var/lib/mysql:cached

  redis:
    image: redis
    ports:
      - "6378:6379"