app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /

user:
    resource: '@UserBundle/Resources/config/routing.yml'
    prefix:   /

logout:
    path: /logout

movies:
    type: rest
    resource: RestApiBundle\Controller\MoviesController

movies_post:
    path: /movies
    methods: [POST]
    defaults:
        _controller: RestApiBundle\Controller\MoviesController:postMoviesAction
        _format: json