app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /

user:
    resource: '@UserBundle/Resources/config/routing.yml'
    prefix:   /

logout:
    path: /logout

movies:
    type: rest
    resource: RestApiBundle\Controller\MoviesController

movies_post:
    path: /movies
    methods: [POST]
    defaults:
        _controller: RestApiBundle\Controller\MoviesController:postMoviesAction
        _format: json

movies_patch:
    path: /movies/{movie}
    methods: [PATCH]
    defaults:
        _controller: AppBundle\Controller\MoviesController:patchMovieAction
        _format: json

humans:
    type: rest
    resource: RestApiBundle\Controller\HumansController

humans_post:
    path: /humans
    methods: [POST]
    defaults:
        _controller: RestApiBundle\Controller\HumansController:postHumansAction
        _format: json

movies_roles_post:
    path: /movies/{movie}/roles
    methods: [POST]
    defaults:
        _controller: RestApiBundle\Controller\MoviesController:postMovieRolesAction
        _format: json
users:
    resource: RestApiBundle\Controller\UsersController
    type: rest

users_post:
        path: /users
        methods: [POST]
        defaults:
            _controller: RestApiBundle\Controller\UsersController:postUserAction
            _format: json

users_patch:
    path: /users/{theUser}
    methods: [PATCH]
    defaults:
        _controller: RestApiBundle\Controller\UsersController:patchUserAction
        _format: json


tokens:
    resource: RestApiBundle\Controller\TokensController
    type: rest