app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /

user:
    resource: '@UserBundle/Resources/config/routing.yml'
    prefix:   /

logout:
    path: /logout