# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_database_users:
            entity: { class: UserBundle:User, property: username}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #form_login:
            #   login_path: login
            #   check_path: login
            guard:
                authenticators:
                    - app.security.login_form_authenticator

#        secured_area:
            logout:
               path:   /logout
               target: /

    access_control:
        # require ROLE_ADMIN for /admin*
#        - { path: ^/admin, roles: ROLE_ADMIN }
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
