# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User: bcrypt
        RestApiBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_database_users:
            entity: { class: UserBundle:User, property: username}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: true
            guard:
                authenticators:
                    - app.security.login_form_authenticator

        secured_api:
            anonymous: true
            stateless: true
            guard:
                authenticators:
                   - RestApiBundle\Security\TokenAuthenticator


#        secured_area:
#            logout:
#               path:   /logout
#               target: /

#    access_control:
#          role_hierarchy:
#                  ROLE_ADMIN:       ROLE_USER
#                  ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        # require ROLE_ADMIN for /admin*
        #- { path: ^/posts, roles: ROLE_USER }
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
