<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 * @param $username
	 *
	 * @return mixed
	 */
	public function findOneByUsernameOrEmail($username)
	{
		try {
			return $this->createQueryBuilder( 'u' )
			            ->andWhere( 'u.username = :username OR u.email = :email' )
			            ->setParameter( 'username', $username )
			            ->setParameter( 'email', $username )
			            ->getQuery()
			            ->getOneOrNullResult();
		} catch ( NonUniqueResultException $e ) {
		}
	}
}
