<?php

namespace BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPostsByCategory(){
        return $this->createQueryBuilder('post')
            ->andWhere('post.category_id = :id')
            ->setParameter('id', $this->getId())
            ->getQuery()
            ->execute();

    }
}
