blog_post:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

blog_post_annotations:
    resource: "@BlogBundle/Controller"
    type:   annotation

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
